apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv-volume
  labels:
    type: local
spec:
  storageClassName: images
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$HOME/mnt/data"