apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: sparkworker
  name: sparkworker
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "41352"
      port: 41352
      targetPort: 41352
  selector:
    io.kompose.service: sparkworker
  type: NodePort
status:
  loadBalancer: {}
