apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent-1
  labels:
    type: local
spec:
  storageClassName: agent-1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "volume/agent-1"