apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent-0
  labels:
    type: local
spec:
  storageClassName: agent-0
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "$HOME/mnt/agent-0"