apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-executor
  labels:
    type: local
spec:
  storageClassName: code-executor
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/code-executor"