apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-api
  labels:
    type: local
spec:
  storageClassName: database-api
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "volume/database-api"