apiVersion: v1
kind: PersistentVolume
metadata:
  name: model
  labels:
    type: local
spec:
  storageClassName: model
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/learningOrchestra/model"