apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer
  labels:
    type: local
spec:
  storageClassName: portainer
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/portainer"